name: Publish release

on:
  release:
    types: [published]

jobs:
  publish-maven:
    runs-on: macos-latest

    steps:
      - name: Setup JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
      - name: Cache build deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.konan/cache
            ~/.konan/dependencies
          key: build-deps-${{ hashFiles('~/.gradle/**') }}-${{ hashFiles('~/.konan/**') }}

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # If we split on '/' and take the 3rd value,
        # we can get the release name.
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -Pversion=${NEW_VERSION} publish
